### ISSUE TITLE
support for news based comments

### ISSUE THREAD

**Issue by topsnet-holgerd** [teamneusta/pw_comments#24]
Sorry for my latest post, I now found the problem:
No comments will be written to the database and no notification will be send, when a routeEnhancer is added to config.yaml in order to have an XML sitemap:
```
  PageTypeSuffix:
    type: PageType
    default: '/'
    index: ''
    map:
      news_sitemap.xml: 1533906435

```
I don't know why this happens, would you please explain (and perhaps add it to Known Issues)?
I left a bugreport at forge.typo3.org: [https://forge.typo3.org/issues/106776](url)
